# Inspiration:
# - https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
name: üê≥ Docker images for Airflow

# See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-38
on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: false
        type: string
      environment:
        required: true
        type: string
  workflow_call:
    inputs:
      image_tag:
        required: false
        type: string
      environment:
        required: true
        type: string

env:
  SCALEWAY_REGISTRY: rg.fr-par.scw.cloud
  SCALEWAY_NAMESPACE: ns-qfdmo

jobs:
  build-and-push-image:
    name: üê≥ Build and push Docker images
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # https://github.com/docker/login-action
      - name: "[üü£ Scaleway] Log in to the Scaleway Container registry"
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.SCALEWAY_REGISTRY }}
          username: nologin
          password: ${{ secrets.SCALEWAY_DOCKER_SECRET }}

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      # https://github.com/docker/metadata-action
      - name: "[üü£ Scaleway] Extract metadata (tags, labels) for Docker"
        id: airflow_scheduler_meta_scaleway
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.SCALEWAY_REGISTRY }}/${{ env.SCALEWAY_NAMESPACE }}/airflow-scheduler

      # https://github.com/docker/build-push-action
      - name: "[üü£ Scaleway] Build and push Docker image (airflow-scheduler)"
        id: build-and-push-scheduler
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          cache-from: type=gha,scope=scheduler
          cache-to: type=gha,scope=scheduler,mode=max
          push: true
          tags: ${{ inputs.image_tag && format('{0}/{1}/{2}:{3}', env.SCALEWAY_REGISTRY, env.SCALEWAY_NAMESPACE, 'airflow-scheduler', inputs.image_tag) || steps.airflow_scheduler_meta_scaleway.outputs.tags }}
          labels: ${{ steps.airflow_scheduler_meta_scaleway.outputs.labels }}
          file: data-platform/airflow-scheduler.Dockerfile

      - name: "[üü£ Scaleway] Extract metadata (tags, labels) for Docker"
        id: airflow_webserver_meta_scaleway
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.SCALEWAY_REGISTRY }}/${{ env.SCALEWAY_NAMESPACE }}/airflow-webserver

      - name: "[üü£ Scaleway] Build and push Docker image (airflow-webserver)"
        id: build-and-push-webserver
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          cache-from: type=gha,scope=webserver
          cache-to: type=gha,scope=webserver,mode=max
          push: true
          tags: ${{ inputs.image_tag && format('{0}/{1}/{2}:{3}', env.SCALEWAY_REGISTRY, env.SCALEWAY_NAMESPACE, 'airflow-webserver', inputs.image_tag) || steps.airflow_webserver_meta_scaleway.outputs.tags }}
          labels: ${{ steps.airflow_webserver_meta_scaleway.outputs.labels }}
          file: data-platform/airflow-webserver.Dockerfile
