on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag_name:
        type: string
        required: true

jobs:
  airflow_docker:
    name: üê≥ Airflow Docker
    uses: ./.github/workflows/_airflow-build-and-push-docker.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      image_tag: ${{ inputs.tag_name }}
      environment: ${{ inputs.environment }}


  deploy_scaleway_scheduler:
    name: üü£‚è≥ Scaleway Airflow scheduler
    secrets: inherit # pragma: allowlist secret`
    uses: ./.github/workflows/_scaleway-container-deploy.yml
    needs: [airflow_docker]
    with:
      container_key: SCALEWAY_AIRFLOW_SCHEDULER_CONTAINER_ID
      registry_image: ${{ format('{0}:{1}', 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-scheduler', inputs.tag_name) }}
      environment: ${{ inputs.environment }}

  deploy_scaleway_webserver:
    secrets: inherit # pragma: allowlist secret`
    name: üü£‚è≥ Scaleway Airflow webserver
    needs: [airflow_docker]
    uses: ./.github/workflows/_scaleway-container-deploy.yml
    with:
      container_key: SCALEWAY_AIRFLOW_WEBSERVER_CONTAINER_ID
      registry_image: ${{ format('{0}:{1}', 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-webserver', inputs.tag_name) }}
      environment: ${{ inputs.environment }}

# Address actions/missing-workflow-permissions rule in
# code scanning alerts
permissions:
  contents: read

