on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag_name:
        type: string
        required: true

jobs:
  airflow_docker:
    name: üê≥ Airflow Docker
    uses: ./.github/workflows/_airflow-build-and-push-docker.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      image_tag: ${{ inputs.tag_name }}
      environment: ${{ inputs.environment }}

  # WILL BE DEPRECATED SOON
  deploy_airflow-webserver:
    if: ${{ inputs.environment == 'prod' }}
    name: üîÑ CleverCloud Webserver
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_SCHEDULER_CLEVERCLOUD_APP_NAME

  # WILL BE DEPRECATED SOON
  deploy_airflow-scheduler:
    if: ${{ inputs.environment == 'prod' }}
    name: ‚è≥ CleverCloud Scheduler
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_WEBSERVER_CLEVERCLOUD_APP_NAME

  deploy_scaleway_scheduler:
    name: üü£‚è≥ Scaleway Airflow scheduler
    secrets: inherit # pragma: allowlist secret`
    uses: ./.github/workflows/_scaleway-container-deploy.yml
    needs: [airflow_docker]
    with:
      environment: ${{ inputs.environment }}
      container_key: SCALEWAY_AIRFLOW_SCHEDULER_CONTAINER_ID
      registry_image: ${{ format('{0}:{1}', 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-scheduler', inputs.tag_name) }}

  deploy_scaleway_webserver:
    secrets: inherit # pragma: allowlist secret`
    name: üü£‚è≥ Scaleway Airflow webserver
    needs: [airflow_docker]
    uses: ./.github/workflows/_scaleway-container-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      container_key: SCALEWAY_AIRFLOW_WEBSERVER_CONTAINER_ID
      registry_image: ${{ format('{0}:{1}', 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-webserver', inputs.tag_name) }}

# Address actions/missing-workflow-permissions rule in
# code scanning alerts
permissions:
  contents: read

