on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag_name:
        type: string
        required: true

jobs:
  deploy_airflow-webserver:
    if: ${{ inputs.environment == 'prod' }}
    name: üîÑ Airflow webserver
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_SCHEDULER_CLEVERCLOUD_APP_NAME

  deploy_airflow-scheduler:
    if: ${{ inputs.environment == 'prod' }}
    name: ‚è≥ Airflow scheduler
    uses: ./.github/workflows/_deploy-on-clever-cloud.yml
    secrets: inherit # pragma: allowlist secret`
    with:
      environment: ${{ inputs.environment }}
      # Name of environment variable set in github environment
      app_name_key: AIRFLOW_WEBSERVER_CLEVERCLOUD_APP_NAME

  deploy_scaleway_scheduler:
    secrets: inherit # pragma: allowlist secret`
    name: üü£‚è≥ Scaleway Airflow scheduler
    uses: ./.github/workflows/_scaleway_container_deploy.yml
    with:
      environment: ${{ inputs.environment }}
      container_key: SCALEWAY_AIRFLOW_SCHEDULER_CONTAINER_ID
      registry_image: format({0}:{1}, 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-scheduler', inputs.tag_name)

  deploy_scaleway_webserver:
    secrets: inherit # pragma: allowlist secret`
    name: üü£‚è≥ Scaleway Airflow webserver
    uses: ./.github/workflows/_scaleway_container_deploy.yml
    with:
      environment: ${{ inputs.environment }}
      container_key: SCALEWAY_AIRFLOW_WEBSERVER_CONTAINER_ID
      registry_image: format({0}:{1}, 'rg.fr-par.scw.cloud/ns-qfdmo/airflow-webserver', inputs.tag_name)

# Address actions/missing-workflow-permissions rule in
# code scanning alerts
permissions:
  contents: read

