name: ðŸª¢ Non-rÃ©gression

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

env:
  PGHOST: localhost
  PGPORT: 5432
  PGUSER: webapp
  POSTGRES_USER: webapp
  POSTGRES_PASSWORD: webapp # pragma: allowlist secret
  POSTGRES_DB: webapp # pragma: allowlist secret
  PGPASSWORD: webapp # pragma: allowlist secret
  PGDATABASE: webapp
  UV_PROJECT_ENVIRONMENT: .venv
  BASE_URL: http://localhost:8000
  DATABASE_URL: postgres://webapp:webapp@localhost:5432/webapp # pragma: allowlist secret
  SECRET_KEY: coucou # pragma: allowlist secret
  CI: true

jobs:
  regression:
    name: Regression â€“ ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: main
            ref: main
            update_snapshots: true
            playwright_config: next/playwright.regression.ts
            upload: true

          - name: current
            ref: ${{ github.ref }}
            update_snapshots: false
            playwright_config: playwright.regression.ts
            download: true

    services:
      postgres:
        image: postgis/postgis:15-3.3-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 50
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.ref }}
          path: app

      - name: Checkout main (for comparison)
        if: matrix.name == 'main'
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          build: "true"

      - name: Setup backend
        uses: ./.github/actions/setup-backend
        with:
          uv-groups: "--group dev"

      - name: Install GIS packages
        uses: ./.github/actions/install-gis

      - name: Get current date
        id: date
        run: echo "value=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Prepare Django database
        uses: ./.github/actions/prepare-django-db
        with:
          cache-key: db-dump-${{ hashFiles('**/migrations/**/*.py') }}-${{ steps.date.outputs.value }}
          sample-db-uri: ${{ secrets.SAMPLE_DB_URI }}
          database-url: ${{ env.DATABASE_URL }}
          local-dump-path: database-dump.pgdump

      - name: collectstatic
        run: make collectstatic

      - name: Restore database
        uses: ./.github/actions/pg-restore
        with:
          database-url: ${{ env.DATABASE_URL }}
          dump-path: database-dump.pgdump

      - name: Download baseline screenshots
        if: matrix.download
        uses: actions/download-artifact@v4
        with:
          name: regression-screenshots
          path: screenshots

      - name: Run server
        run: uv run python manage.py runserver --noreload &

      - name: Wait for server
        run: |
          timeout 20 sh -c 'until curl -s $BASE_URL > /dev/null; do sleep 1; done'
          sleep 2

      - name: Run Playwright
        run: |
          if [ "${{ matrix.update_snapshots }}" = "true" ]; then
            npx playwright test --update-snapshots --config=${{ matrix.playwright_config }}
          else
            npx playwright test --config=${{ matrix.playwright_config }}
          fi
        env:
          SCREENSHOT_BASE_PATH: ${{ github.workspace }}/screenshots

      - name: Upload baseline screenshots
        if: matrix.upload
        uses: actions/upload-artifact@v4
        with:
          name: regression-screenshots
          path: screenshots

permissions:
  contents: read
