name: "ðŸŸ£ Scaleway Container Registry: delete old tags"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * SUN"

env:
  TAGS_TO_KEEP: 30
  TOKEN: ${{ secrets.SCALEWAY_DEPLOY_KEY }}
  #https://console.scaleway.com/registry/namespaces/fr-par/08bcc090-f2e5-458a-8b13-f40016276b9d
  NAMESPACE_ID: "08bcc090-f2e5-458a-8b13-f40016276b9d"

permissions:
  contents: read

jobs:
  delete_old_tags:
    name: Delete old tags
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python scripts/infrastructure/delete_old_images.py